### ISSUE TITLE
bug with `\grid@unique@test`

### ISSUE THREAD

**Issue by mbertucci47** [komascript/gridset#1]
Found by @u-fischer in https://github.com/latex3/tagging-project/issues/559.

The code does
```tex
\AtBeginDocument{%
  \global\let\grid@unique@test\@gobble
}
```
but it should be
```tex
\AtBeginDocument{%
  \global\let\grid@unique@test\@gobbletwo
}
```
since `\grid@unique@test` takes two arguments.

**Comment by komascript** [comment]
Thank you for the report. I've fixed the issue and also updated the tests and the build process.

Many thanks also to @u-fischer for the analysation of the issue.
